[project]
name = "londonaicentre-schemallama-docsynth" 
description = "SchemaLlama docsynth"
authors = [
    { name = "Dr. Joe Zhang", email = "jzhang@nhs.net" }
]
version = "1.0.0"
requires-python = ">=3.12"
license = "CC-BY-NC-ND-4.0"
dependencies = [
    "londonaicentre-schemallama-utils",
    "londonaicentre-schemallama-types",
    "pyyaml>=6.0.3",
    "google-generativeai>=0.8.5",
]
[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"
[tool.uv.sources]
londonaicentre-schemallama-utils = { path = "../utils", editable = true }
londonaicentre-schemallama-types = { path = "../types", editable = true }
[tool.setuptools.package-data]
docsynth = [
    "py.typed"
]
[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "ruff>=0.14.6",
    "types-pyyaml>=6.0.12.20250915",
]

