[project]
name = "londonaicentre-docsynth" 
description = "SchemaLlama docsynth"
authors = [
    { name = "Dr. Joe Zhang", email = "jzhang@nhs.net" }
]
version = "1.0.0"
requires-python = ">=3.12"
license = "CC-BY-NC-ND-4.0"
dependencies = [
    "pyyaml>=6.0.3",
    "google-generativeai>=0.8.5",
    "pydantic-settings>=2.12.0",
    "londonaicentre-mesa-utils>=1.2.0",
    "londonaicentre-mesa-types>=2.3.0",
]
[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"
[tool.setuptools.package-data]
docsynth = [
    "assets/*/profiles/*",
    "assets/*/prompts/*",
    "assets/*/structure/*",
    "assets/*/*.yml",
    "config/*.yml",
    "py.typed"
]
[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.6",
    "types-pyyaml>=6.0.12.20250915",
]

